name: krotov
channels:
  - defaults
  - conda-forge
dependencies:
  - matplotlib=3.1.0
  - python=3.6.7
  - scipy=1.2.1
  - qutip=4.4.1
  - pip:
    - watermark
    - git+https://github.com/qucontrol/krotov.git@master#egg=krotov
